version: "3.9"
services:
  timedb:
    build: ./db
    env_file: db.conf 
    ports: 
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/timescale/data
  server:
    build: ./server 
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    volumes: 
      - .:/code 
    env_file: db.conf 
    depends_on: 
      - timedb 